version: '3.8'

services:
  backend:
    image: <your_docker_username>/employee-leave-management-backend:latest
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/leave_management
      - JWT_SECRET=506a326e4b051d17f7ea45d93517792810f1df43fd09238c29bca533e3caf1731a97badb480343dc857b863ddf6de9a5c90a4c0ed756b53e30c17843d4f3ac91
    depends_on:
      - mongo

  frontend:
    image: <your_docker_username>/employee-leave-management-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data: